apiVersion: v1
kind: ServiceAccount
metadata:
  name: stream-svc-sa
  labels:
    app: stream-svc
  annotations:
    example-annotation: "value"
automountServiceAccountToken: false
#set to false to disable automatic mounting of the service account token
# This is useful for security reasons, as it prevents the service account token from being mounted into pods that don't need it.

